### ISSUE TITLE
旋转屏幕崩溃

### ISSUE THREAD

**Issue by abbuaus** [fgsqme/Android_Native_Surface#12]
如果增加字体，那旋转屏幕就会马上崩溃
bool DrawVulkan::initDraw(uint32_t _screen_x, uint32_t _screen_y, int flags, bool log)

    ImFontConfig font_cfg;
    font_cfg.SizePixels = 22.0f;
    io.Fonts->AddFontDefault(&font_cfg);
    io.Fonts->AddFontFromMemoryTTF((void *) OPPOSans_H, OPPOSans_H_size, 35.0f, NULL, io.Fonts->GetGlyphRangesChineseFull());

Pointer tag for 0x5c5cad55e8 was truncated, see 'https://source.android.com/devices/tech/debug/tagged-pointers'.

**Comment by abbuaus** [comment]
用另外一个人的方法，去掉shutdown(); 然后改这里可以解决崩溃
    native_window = externFunction.createNativeWindow("Ssage",
                                                      _screen_x , _screen_y, 1, f, false);
但是横屏帧率低很多

**Comment by fgsqme** [comment]
这个问题我也在研究，但是也没解决
