### ISSUE TITLE
图中的显示另一个手机画面有安卓代码参考吗

### ISSUE THREAD

**Issue by TangStudio** [fgsqme/Android_Native_Surface#8]
如题，感谢

**Comment by fgsqme** [comment]
就是代码中的[recordReceive.cpp](https://github.com/fgsqme/Android_Native_Surface/blob/main/screenRecord/recordReceive.cpp)

**Comment by TangStudio** [comment]
不好意思，我对cpp不是很熟悉，请问如果要在安卓APP里集成您这个库的功能，需要做什么呢？感谢

**Comment by fgsqme** [comment]
录屏端的话就编译screenRecord.cpp成可执行文件执行就行了，但是需要root权限，接收端App你可以找一个h264解码库解码播放就行了

**Comment by fgsqme** [comment]
如果你想用app端实现录屏共享的话，此项目可能不太合适，你需要去调用系统对外提供的api 实现

**Comment by TangStudio** [comment]
我这边是想在系统桌面上做一个悬浮窗，实时显示第三方APP的画面，用你这个库是不是就不太合适了

**Comment by fgsqme** [comment]
可以做，但是要会c++

**Comment by TangStudio** [comment]
录屏似乎都是只能把整个屏幕的画面都录进去，除了修改aosp中录屏这块的代码外，能通过写cpp代码让录屏是区域录屏（只录屏幕上某个区域的画面）吗？

**Comment by fgsqme** [comment]
目前没办法，这块没研究过，但是应该可行的
